# Generated by Django 4.0.6 on 2022-08-10 23:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='install_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date bees installed'),
        ),
        migrations.AddField(
            model_name='hive',
            name='loc_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='hive',
            name='loc_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='hive',
            name='location_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Hive location'),
        ),
        migrations.AddField(
            model_name='hive',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='appuser',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of inspection'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Hive is active'),
        ),
    ]
