# Generated by Django 4.0.6 on 2022-08-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0002_hive_install_date_hive_loc_lat_hive_loc_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='removal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date removed'),
        ),
    ]
