# Generated by Django 4.0.6 on 2022-08-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0004_alter_hive_install_date_alter_hive_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='pollen_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pollen count'),
        ),
    ]
