# Generated by Django 4.0.6 on 2022-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0006_alter_hive_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='loc_lat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='loc_long',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Longitude'),
        ),
    ]
