# Generated by Django 4.0.6 on 2022-08-13 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0007_alter_hive_loc_lat_alter_hive_loc_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='install_date',
            field=models.CharField(blank=True, default=datetime.date.today, max_length=10, null=True, verbose_name='Date bees installed'),
        ),
    ]
