# Generated by Django 4.0.6 on 2022-08-13 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0008_alter_hive_install_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='install_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date bees installed'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='loc_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='hive',
            name='loc_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
