# Generated by Django 4.0.6 on 2022-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0009_alter_hive_install_date_alter_hive_loc_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='location_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Hive location'),
        ),
    ]
