# Generated by Django 4.0.6 on 2022-08-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0010_alter_hive_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
