# Generated by Django 4.0.6 on 2022-08-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0011_alter_hive_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='breed',
            field=models.CharField(default=None, max_length=9, verbose_name='Bee breed'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='depth',
            field=models.CharField(default=None, max_length=7, verbose_name='Hive depth'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='frames',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Hive frames'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='loc_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=8, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='loc_long',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=8, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='location_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Hive location'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='photo_url',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='removal_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date removed'),
        ),
    ]
