# Generated by Django 4.0.6 on 2022-08-13 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0013_alter_inspection_brood_alter_inspection_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='appuser',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
