# Generated by Django 4.0.6 on 2022-08-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0014_alter_inspection_appuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='hive',
            new_name='curr_hive',
        ),
    ]
