# Generated by Django 4.0.6 on 2022-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess5_app', '0016_remove_hive_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='pollen_type',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Pollen types'),
        ),
    ]
